name: Test build CD Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build Project
        run: go build ./main.go
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hodor
          path: dist
