name: Test build CD Go

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Create output directory
        run: mkdir dist && echo "Directory created"

      - name: Build Project
        run: go build -o dist/hodor ./main.go && ls -l dist
        
      # - name: Upload Artifacts

      #   uses: actions/upload-artifact@v3

      #   with: 
      #       name: hodor
      #       path: "dist/hodor"

      # - name: Show directory listing
      #   run: ls -l dist


      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: hodor
            
