name: Test build CD Go

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build Project
        run: go build -o hodor ./main.go
        
      - name: Upload Artifacts

        uses: actions/upload-artifact@v3

        with: 

            name: hodor

            path: "**/dist/hodor"
            
  Download:
      runs-on: ubuntu-latest
      needs: Build
      steps:
          - name: download
            uses: actions/download-artifact@v3
            with:
                name: hodor
